#!/usr/bin/env node
// Vendors shared runtime contracts from src/shared/ into cli/src/vendor/.
//
// The CLI package compiles with rootDir=cli/src, so it cannot import ../../src/shared
// directly. Instead of hand-maintaining copies (which drift), this script copies the
// shared sources verbatim — rewriting relative imports for the flat vendor layout —
// and runs automatically before `npm run typecheck:cli` / `npm run cli:build`.
//
// Usage:
//   node cli/scripts/sync-shared.mjs           # write vendored copies
//   node cli/scripts/sync-shared.mjs --check   # exit 1 if vendored copies are stale

/* eslint-disable @typescript-eslint/explicit-function-return-type -- plain Node script */
import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..')
const vendorDir = join(repoRoot, 'cli', 'src', 'vendor')

/** @type {Array<{ source: string; target: string; rewrites?: Array<[string, string]> }>} */
const SHARED_FILES = [
  {
    source: 'src/shared/runtime-contracts/generated/contracts.ts',
    target: 'runtime-contracts.ts'
  },
  {
    source: 'src/shared/agent-runtime-v2.ts',
    target: 'agent-runtime-v2.ts'
  },
  {
    source: 'src/shared/worker-contracts/generated/contracts.ts',
    target: 'worker-contracts.ts'
  },
  {
    source: 'src/shared/native-worker-protocol.ts',
    target: 'native-worker-protocol.ts',
    rewrites: [["'./worker-contracts/generated/contracts'", "'./worker-contracts.js'"]]
  },
  {
    source: 'src/shared/worker-http-channel.ts',
    target: 'worker-http-channel.ts'
  },
  {
    source: 'src/shared/routin-credential.ts',
    target: 'routin-credential.ts'
  }
]

const checkOnly = process.argv.includes('--check')

function renderVendorFile({ source, rewrites }) {
  const sourcePath = join(repoRoot, source)
  let content = readFileSync(sourcePath, 'utf8')
  for (const [from, to] of rewrites ?? []) {
    if (!content.includes(from)) {
      throw new Error(`sync-shared: expected import "${from}" not found in ${source}`)
    }
    content = content.replaceAll(from, to)
  }
  const header =
    `// AUTO-GENERATED by cli/scripts/sync-shared.mjs from ${source} — do not edit.\n` +
    '// Edit the shared source, then run `npm run cli:sync-shared` (also runs before CLI builds).\n\n'
  return header + content
}

const stale = []
mkdirSync(vendorDir, { recursive: true })
for (const file of SHARED_FILES) {
  const expected = renderVendorFile(file)
  const targetPath = join(vendorDir, file.target)
  const current = existsSync(targetPath) ? readFileSync(targetPath, 'utf8') : null
  if (current === expected) continue
  if (checkOnly) {
    stale.push(file.target)
    continue
  }
  writeFileSync(targetPath, expected)
  console.log(`sync-shared: updated cli/src/vendor/${file.target}`)
}

if (checkOnly && stale.length > 0) {
  console.error(
    `sync-shared: vendored copies out of date: ${stale.join(', ')}. Run \`npm run cli:sync-shared\`.`
  )
  process.exit(1)
}
